version: '3.8'

services:
  node1:
    image: jrkalf/kryptokrona-node:latest
    container_name: kryptokrona-node1
    ports:
      - "11898:11898"
      - "11897:11897"
    volumes:
      - ./blockloc:/kryptokrona/blockloc
    command: >
      /bin/sh -c " ./kryptokronad --enable-cors=* --rpc-bind-ip=0.0.0.0 --rpc-bind-port=11898 --data-dir /kryptokrona/blockloc --log-level 3 "
    restart: always
