apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kryptokrona-node
  namespace: kryptokrona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  volumeName: kryptokrona-node
  storageClassName: <YOUR STORAGECLASS NAME>
  volumeMode: Filesystem