apiVersion: v1
kind: Service
metadata:
  name: kryptokrona-node
  namespace: kryptokrona
spec:
  selector:
    app: kryptokrona-node
  ports:
    - port: 11898
      targetPort: 11898
      name: "exposed-port"
    - port: 11897
      targetPort: 11897
      name: "inbound-to-node"
  type: LoadBalancer