apiVersion: v1
kind: PersistentVolume
metadata:
  name: kryptokrona-node
spec:
  storageClassName: <YOUR STORAGECLASS NAME>
  capacity:
    storage: 50Gi
  nfs:
    server: <enter IP of NFS here!>
    path: <enter folderpath here starting with / >
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kryptokrona-node
  namespace: kryptokrona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  volumeName: kryptokrona-node
  storageClassName: <YOUR STORAGECLASS NAME>
  volumeMode: Filesystem